Codex/src/java/az/codex/domain/Contact.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package az.codex.domain;

import java.util.Date;
import javax.naming.Name;
import org.apache.commons.validator.EmailValidator;

/**
 *
 * @author hikmet
 */
public class Contact extends BaseDomain
{
    private String Name;
    private String email;
    private String message;
    private Date sendDate;

    public Contact(String Name, String email, String message,Date sendDate)
    {
        this.Name = Name;
        this.email = email;
        this.message = message;
        this.sendDate = sendDate;
    }

    public Date getSendDate()
    {
        return sendDate;
    }

    public void setSendDate(Date sendDate)
    {
        this.sendDate = sendDate;
    }

    public String getName()
    {
        return Name;
    }

    public void setName(String Name)
    {
        this.Name = Name;
    }

    public String getEmail()
    {
        return email;
    }

    public void setEmail(String email)
    {
        this.email = email;
    }

    public String getMessage()
    {
        return message;
    }

    public void setMessage(String message)
    {
        this.message = message;
    }

    public long getId()
    {
        return id;
    }

    public void setId(long id)
    {
        this.id = id;
    }

    public Status getStatus()
    {
        return status;
    }

    public void setStatus(Status status)
    {
        this.status = status;
    }
    
    
}

Codex/web/inc/adminsidebar.jsp
<%-- 
    Document   : sidebar
    Created on : Jan 25, 2014, 9:34:08 PM
    Author     : hikmet
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>

            <div id="xx" class="sidebar" style="z-index:100">
                  <!-- Logo starts -->
                  <div class="logo">
                      <a href="index.jsp"><img style="width:100%" src="/img/logo.png"></img></a></h1>
                  </div>
                  <!-- Logo ends -->
                  <!-- Sidebar buttons starts -->
                  <div class="sidebar-buttons text-center" style="padding-bottom: 10px;">
                     <!-- User button -->
                     <%if(session.getAttribute("user")!=null){%>
                     <div class="btn-group">
                       <a href="profile.jsp" class="btn btn-black btn-xs"><i class="icon-user"></i></a>
                       <a href="profile.jsp" class="btn btn-danger btn-xs">User</a>
                     </div>
                     <!-- Lock button -->
                     <div class="btn-group">
                       <a href="lock.jsp" class="btn btn-black btn-xs"><i class="icon-lock"></i></a>
                       <a href="lock.jsp" class="btn btn-danger btn-xs">Lock</a>
                     </div>
                     <%}%>
                     <!-- Logout button -->
                     <div class="btn-group">
                       <a href="login.jsp" class="btn btn-black btn-xs"><i class="icon-off"></i></a>
                       <a href="login.jsp" class="btn btn-danger btn-xs"><%if(session.getAttribute("user")!=null){%>Logout <%}else{%>Login<%}%></a>
                     </div>
                  </div>
                  <!-- Sidebar buttons ends -->
                  
                  <!-- Sidebar navigation starts -->
				  
				  <div class="sidebar-dropdown"><a href="#">Navigation</a></div>
				  
                  <div class="sidey">
                     <ul class="nav">
                         <!-- Main navigation. Refer Notes.txt files for reference. -->
                         
                         <!-- Use the class "current" in main menu to hightlight current main menu -->
                         <li class="current"><a href="index.jsp"><i class="icon-home"></i> Home</a></li>
                         <li class="has_submenu">
                           <a href="#">
                              <i class="icon-bug"></i> Stores <span class="label label-darky">3</span>
                              <span class="caret pull-right"></span>
                           </a>
                             <ul>
                                 <li><a href="store.jsp?id=1"><i class="icon-double-angle-right"></i> Restaurant N1</a></li>
                                 <li><a href="store.jsp?id=2"><i class="icon-double-angle-right"></i> Restaurant N2</a></li>
                                 <li><a href="store.jsp?id=3"><i class="icon-double-angle-right"></i> Clothes Shop N1</a></li>
                             </ul>
                         </li>
                                                  
                     </ul>               
                  </div>
                  <!-- Sidebar navigation ends -->
                  <!-- Sidebar status ends -->
            </div>

Codex/web/inc/footer.jsp
                    <div class="footer">
                        <div class="container">
                            <!-- Footer content -->
                            <div class="footer-content">
                                <div class="row">
                                    <div class="col-md-3 col-xs-12">
                                        <div class="footer-widget">
                                            <!-- Heading -->
                                            <h5><span><i class="icon-puzzle-piece"></i></span> Navigation Menu</h5>
                                            <!-- Navigate menu -->
                                            <ul class="menu">
                                                <!-- Menu list -->
                                                <li><a href="index.jsp"><i class="icon-home"></i> Home</a></li>
                                                <li><a href="category.jsp"><i class="icon-tasks"></i> Category</a></li>
                                                <li><a href="profile.jsp"><i class="icon-user"></i> Profile</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="col-md-3 col-xs-12">
                                        <div class="footer-widget">
                                            <!-- Heading -->
                                            <h5><span><i class="icon-phone"></i></span> Contact Us</h5>
                                            <!-- Email and Phone number -->
                                            <p><i class="icon-envelope"></i> <a href="#">Helelik emailimiz yoxdu</a><br />
                                                <i class="icon-phone"></i> Helelik telefonumuz da yoxdu</p>
                                            <!-- Social icons -->
                                            
                                        </div>
                                    </div>
                                    <div class="col-md-3 col-xs-12">
                                        <div class="footer-widget">
                                            <!-- Heading -->
                                            <h5><span><i class="icon-gears"></i></span> Categories</h5>
                                            <!-- Navigate menu -->
                                            <ul>
                                                <!-- navigation menu item -->
                                                <li><a href="/category.jsp?id=1">Restaurant</a></li>
                                                <li><a href="/category.jsp?id=1">Fashion</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="col-md-3 col-xs-12">
                                        <div class="footer-widget">
                                            <!-- Heading -->
                                            <h5><span><i class="icon-envelope"></i></span> Subscribe Now</h5>
                                            <p>Email islemir...</p>
                                            <!-- form -->
                                            <form>
                                                <div class="input-group">
                                                    <!-- form input -->
                                                    <input type="text" class="form-control" placeholder="Email">
                                                    <span class="input-group-btn">
                                                        <!-- join button -->
                                                        <button class="btn btn-info" type="button"><i class="icon-envelope"></i></button>
                                                    </span>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- Footer Copyright -->
                            <div class="footer-copyright">
                                <p>&copy; Copyright 2013 - <a href="#">Codex Software</a></p>
                            </div>
                        </div>
                    </div>

Codex/web/inc/sidebar.jsp
<%-- 
    Document   : sidebar
    Created on : Jan 25, 2014, 9:34:08 PM
    Author     : hikmet
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>

            <div id="xx" class="sidebar" style="z-index:100">
                  <!-- Logo starts -->
                  <div class="logo">
                      <a href="index.jsp"><img style="width:100%" src="/img/logo.png"></img></a></h1>
                  </div>
                  <!-- Logo ends -->
                  <!-- Sidebar buttons starts -->
                  <div class="sidebar-buttons text-center" style="padding-bottom: 10px;">
                     <!-- User button -->
                     <%if(session.getAttribute("user")!=null){%>
                     <div class="btn-group">
                       <a href="profile.jsp" class="btn btn-black btn-xs"><i class="icon-user"></i></a>
                       <a href="profile.jsp" class="btn btn-danger btn-xs">User</a>
                     </div>
                     <!-- Lock button -->
                     <div class="btn-group">
                       <a href="lock.jsp" class="btn btn-black btn-xs"><i class="icon-lock"></i></a>
                       <a href="lock.jsp" class="btn btn-danger btn-xs">Lock</a>
                     </div>
                      <div class="btn-group">
                       <a href="login.jsp" class="btn btn-black btn-xs"><i class="icon-off"></i></a>
                       <a href="login.jsp" class="btn btn-danger btn-xs">Logout </a>
                     </div>
                     <%}else{%>
                       <div class="btn-group">
                       <a href="login.jsp" class="btn btn-black btn-xs"><i class="icon-user"></i></a>
                       <a href="login.jsp" class="btn btn-danger btn-xs">Register</a>
                     </div>
                     <!-- Logout button -->
                     <div class="btn-group">
                       <a href="login.jsp" class="btn btn-black btn-xs"><i class="icon-off"></i></a>
                       <a href="login.jsp" class="btn btn-danger btn-xs">Login </a>
                     </div><%}%>>
                  </div>
                  <!-- Sidebar buttons ends -->
                  
                  <!-- Sidebar navigation starts -->
				  
				  <div class="sidebar-dropdown"><a href="#">Navigation</a></div>
				  
                  <div class="sidey">
                     <ul class="nav">
                         <!-- Main navigation. Refer Notes.txt files for reference. -->
                         
                         <!-- Use the class "current" in main menu to hightlight current main menu -->
                         <li class="current"><a href="index.jsp"><i class="icon-home"></i> Home</a></li>
                         						 
                         <li class="has_submenu">
                             <a href="#">
                                 <i class="icon-file"></i> Categories <span class="label label-darky">${applicationScope.category.count}</span>
                                 <!-- Icon to show dropdown -->
                                 <span class="caret pull-right"></span>
                             </a>
                             <!-- Sub navigation -->
                             <ul>
                                <!-- Use the class "active" in sub menu to hightlight current sub menu -->
                                <%-- TODO for loop for categories      ${applicationScope.category.name[i]}--%>
                                <li><a href="category.jsp?id=1"><i class="icon-double-angle-right"></i>Restaurants</a></li>
                                <li><a href="category.jsp?id=2"><i class="icon-double-angle-right"></i>Fashion</a></li>
                             </ul>
                         </li>
                         <li><a href="aboutus.jsp"><i class="icon-user"></i> About Us</a></li>
						 <li><a href="contactus.jsp"><i class="icon-phone"></i> Contact Us</a></li>
                         <li class="has_submenu">
                           <a href="#">
                              <i class="icon-bug"></i> Extras <span class="label label-darky">3</span>
                              <span class="caret pull-right"></span>
                           </a>
                             <ul>
                                 <li><a href="service.jsp"><i class="icon-double-angle-right"></i> Services</a></li>
                                 <li><a href="terms.jsp"><i class="icon-double-angle-right"></i> Terms and conditions</a></li>
                                 <li><a href="faq.jsp"><i class="icon-double-angle-right"></i> FAQ</a></li>
                             </ul>
                         </li>
                                                  
                     </ul>               
                  </div>
                  <!-- Sidebar navigation ends -->
                  <!-- Sidebar status ends -->
            </div>